package by.ladyka.poputka.data.entity.roadassistance;

import by.ladyka.poputka.data.entity.Auditable;
import by.ladyka.poputka.data.entity.PoputkaUser;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
@Table(name = "assistance_reviews")
public class AssistanceReview extends Auditable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "request_id", nullable = false)
    private AssistanceRequest request;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reviewee_id", nullable = false)
    private PoputkaUser reviewee;

    @Column(name = "rating", nullable = false)
    private Integer rating;

    @Column(name = "comment")
    private String comment;

    @Column(name = "is_auto_generated", nullable = false)
    private Boolean isAutoGenerated = false;

    @Column(name = "is_moderated", nullable = false)
    private Boolean isModerated = false;

    @Column(name = "moderator_comment")
    private String moderatorComment;

    public PoputkaUser getReviewer() {
        return getCreatedUser();
    }
}
