server:
  port: 10001
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
debug: true
application:
  storage:
    documents: /home/user/development/poputka/data
