package by.ladyka.poputka.data.repository.roadassistance;

import by.ladyka.poputka.data.entity.roadassistance.AssistanceReview;
import by.ladyka.poputka.data.entity.roadassistance.AssistanceRequest;
import by.ladyka.poputka.data.entity.PoputkaUser;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface AssistanceReviewRepository extends JpaRepository<AssistanceReview, Long> {
    Optional<AssistanceReview> findByRequestIdAndCreatedUserAndRevieweeId(Long request_id, PoputkaUser createdUser, long reviewee_id);
    
    @Query("SELECT AVG(r.rating) FROM AssistanceReview r WHERE r.reviewee = :reviewee " +
           "AND (r.isAutoGenerated = false OR r.isModerated = true)")
    Double calculateAverageRating(@Param("reviewee") PoputkaUser reviewee);
    
    @Query("SELECT r FROM AssistanceReview r WHERE r.reviewee = :reviewee " +
           "AND (r.isAutoGenerated = false OR r.isModerated = true) " +
           "ORDER BY r.createdDatetime DESC")
    Page<AssistanceReview> findValidReviewsByReviewee(@Param("reviewee") PoputkaUser reviewee, Pageable pageable);
}
