package by.ladyka.poputka.data.dto.roadassistance;

import lombok.Data;

import java.time.Instant;

@Data
public class AssistanceReviewDto {
    private Long id;
    private Long requestId;
    private Long reviewerId;
    private String reviewerName;
    private Long revieweeId;
    private String revieweeName;
    private Integer rating;
    private String comment;
    private Boolean isAutoGenerated;
    private Boolean isModerated;
    private String moderatorComment;
    private Long createdDatetime;
}
