package by.ladyka.poputka.service.roadassistance;

import by.ladyka.poputka.data.entity.PoputkaUser;
import by.ladyka.poputka.data.entity.roadassistance.AssistanceRequest;
import by.ladyka.poputka.data.entity.roadassistance.AssistanceReview;
import by.ladyka.poputka.data.repository.roadassistance.AssistanceReviewRepository;
import by.ladyka.poputka.data.repository.roadassistance.AssistanceRequestRepository;
import by.ladyka.poputka.service.NotificationService;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Objects;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class AssistanceReviewService {
    private final AssistanceReviewRepository assistanceReviewRepository;
    private final AssistanceRequestRepository assistanceRequestRepository;
    private final NotificationService notificationService;
    private final UserRatingService userRatingService;

    @Transactional
    public AssistanceReview createReview(PoputkaUser reviewer, Long requestId, Long revieweeId,
            Integer rating, String comment) {
        AssistanceRequest request = assistanceRequestRepository.findById(requestId)
                .orElseThrow(() -> new IllegalArgumentException("Запрос не найден"));

        // Проверка, что пользователь является участником запроса
        boolean isParticipant = Objects.equals(request.getAuthor().getId(), reviewer.getId()) ;
        //TODO Сделать нормально тут  !!!!!
//                ||
//                (request.getOffers().stream()
//                         .anyMatch(offer -> offer.getHelper().getId().equals(reviewer.getId())));

        if (!isParticipant) {
            throw new IllegalStateException("Только участники запроса могут оставлять отзывы");
        }

        // Проверка, что пользователь не оставляет отзыв самому себе
        if (Objects.equals(reviewer.getId(), revieweeId)) {
            throw new IllegalStateException("Нельзя оставить отзыв самому себе");
        }

        // Проверка существующего отзыва
        Optional<AssistanceReview> existingReview = assistanceReviewRepository
                .findByRequestIdAndCreatedUserAndRevieweeId(requestId, reviewer, revieweeId);

        if (existingReview.isPresent()) {
            throw new IllegalStateException("Вы уже оставили отзыв для этого пользователя по данному запросу");
        }

        // Создание отзыва
        AssistanceReview review = new AssistanceReview();
        review.setRequest(request);
        review.setReviewee(request.getAuthor()); // TODO: Получить реального реципиента отзыва
        review.setRating(rating);
        review.setComment(comment);
        review.setIsAutoGenerated(false);
        review.setIsModerated(false);

        review = assistanceReviewRepository.save(review);

        // Пересчет рейтинга пользователя
        userRatingService.recalculateUserRating(review.getReviewee());

        // Проверка, нужно ли блокировать пользователя
        checkUserBlocking(review.getReviewee());

        return review;
    }
//
//    @Transactional
//    public AssistanceReview createAutoReview(Long requestId, Long reviewerId, Long revieweeId,
//            String comment) {
//        AssistanceRequest request = assistanceRequestRepository.findById(requestId)
//                .orElseThrow(() -> new IllegalArgumentException("Запрос не найден"));
//
//        // Проверка существующего отзыва
//        Optional<AssistanceReview> existingReview = assistanceReviewRepository
//                .findByRequestIdAndCreatedUserAndRevieweeId(requestId, reviewerId, revieweeId);
//
//        if (existingReview.isPresent()) {
//            throw new IllegalStateException("Автоматический отзыв уже существует для этой пары пользователей по данному запросу");
//        }
//
//        // Создание автоматического отзыва
//        AssistanceReview review = new AssistanceReview();
//        review.setRequest(request);
//        review.setReviewee(request.getAuthor()); // TODO: Получить реального реципиента отзыва
//        review.setRating(2); // Низкий рейтинг для автоматических отзывов
//        review.setComment(comment);
//        review.setIsAutoGenerated(true);
//        review.setIsModerated(false);
//
//        review = assistanceReviewRepository.save(review);
//
//        // Пересчет рейтинга пользователя
//        userRatingService.recalculateUserRating(review.getReviewee());
//
//        // Проверка, нужно ли блокировать пользователя
//        checkUserBlocking(review.getReviewee());
//
//        return review;
//    }

    public Page<AssistanceReview> getUserReviews(PoputkaUser user, int page, int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by(Sort.Direction.DESC, "createdAt"));
        return assistanceReviewRepository.findValidReviewsByReviewee(user, pageable);
    }

    public Double getUserAverageRating(PoputkaUser user) {
        return assistanceReviewRepository.calculateAverageRating(user);
    }

    @Transactional
    public AssistanceReview moderateReview(PoputkaUser moderator, Long reviewId, boolean isValid,
            String moderatorComment) {
        AssistanceReview review = assistanceReviewRepository.findById(reviewId)
                .orElseThrow(() -> new IllegalArgumentException("Отзыв не найден"));

        // TODO: Проверка прав модератора

        review.setIsModerated(true);
        review.setModeratorComment(moderatorComment);

        review = assistanceReviewRepository.save(review);

        // Если отзыв признан недействительным, пересчитываем рейтинг
        if (!isValid) {
            userRatingService.recalculateUserRating(review.getReviewee());
            checkUserBlocking(review.getReviewee());
        }

        return review;
    }

    private void checkUserBlocking(PoputkaUser user) {
        Double averageRating = getUserAverageRating(user);

        if (averageRating != null && averageRating < 3.0) {
            user.setRequiresModeration(true);

            // Блокировка создания запросов и откликов
            // TODO: Реализовать блокировку на уровне сервисов

            // Уведомление модераторам
            notificationService.sendNotificationToModerators(
                    "LOW_RATED_USER",
                    "Пользователь с низким рейтингом требует модерации",
                    user.getId()
                                                            );
        }
    }

    public List<AssistanceReview> getReviewsForModeration() {
        // TODO: Реализовать получение отзывов для модерации
        return List.of();
    }
}
